spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/signup?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cpdms1289@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # 테이블을 새로 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 서버 인코딩 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # Thymeleaf 설정
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.example.signup: DEBUG
    org.springframework.web: INFO
  file:
    name: ./logs/application.log

# 네이버 API 설정
naver:
  api:
    client-id: WteM7gNGfkJM9lP0SWpl
    client-secret: knW6aJgVW8
    redirect-uri: http://localhost:8080/login/naver/callback
