spring:
  datasource:
    url: jdbc:mysql://localhost:3306/signup?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: cpdms1289@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${naver.api.client-id}
            client-secret: ${naver.api.client-secret}
            redirect-uri: ${naver.api.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

naver:
  api:
    client-id: WteM7gNGfkJM9lP0SWpl
    client-secret: knW6aJgVW8
    redirect-uri: http://localhost:8080/naver/callback

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc: DEBUG
    org.springframework.web.servlet.handler: DEBUG
    org.springframework.web.servlet.view: DEBUG
    org.springframework.jdbc.core: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.signup: DEBUG
